### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fm.castbox.audiobook.radio.podcast/com.linecorp.linesdk.auth.internal.LineAuthenticationActivity}: java.lang.NullPointerException

### ISSUE THREAD

**Issue by HirotoIchinose** [line/line-platform-feedback#62]
This is Android SDK issue.

- Detailed description of the bug, suggestion, enhancement, or feature request

Our app has the button logging with LINE.
When user tap this button to login, some people get the following error and crash.

- Steps to reproduce the issue

1. Please resolve this issue.
2. Write the reason why this issue is caused.
3. Update your sdk or how to escape this error in our app.

- Logs if available

```
Detail info is:
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fm.castbox.audiobook.radio.podcast/com.linecorp.linesdk.auth.internal.LineAuthenticationActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.linecorp.linesdk.auth.internal.d.d' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.NullPointerException: Attempt to read from field 'int com.linecorp.linesdk.auth.internal.d.d' on a null object reference
at com.linecorp.linesdk.auth.internal.LineAuthenticationActivity.a(SourceFile:11062)
at com.linecorp.linesdk.auth.internal.LineAuthenticationActivity.onCreate(SourceFile:71)
at android.app.Activity.performCreate(Activity.java:6942)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by HirotoIchinose** [comment]
Please Please

**Comment by koichi-ozaki** [comment]
test

**Comment by kazuki-ma** [comment]
Thank you for your feedback. We got similar issue but we can't clear the issue now...

Could you give us the entire code&binary or minimum reproduction code?

**Comment by HirotoIchinose** [comment]
@kazuki-ma Thank you for your reply.

We can see this crash in only Crashlytics and cannot reproduce this crash 
I don't know how to reproduce crash and why it cause.

This may be the reproduction code.

```
private class LineLoginOnClickListener implements OnClickListener {

        @Override
        public void onClick(View v) {
            DataTransferConversionManager.sendLoginEventIfNeeded(getContext(), DataTransferConversionManager.LOGIN_TYPE_LINE);

            doLineLogin();
        }
}

private void doLineLogin() {
        try {
            Intent loginIntent = LineLoginApi.getLoginIntent(getApplicationContext(), Constants.LINE_CHANNEL_ID);
            startActivityForResult(loginIntent, LINE_REQUEST_CODE);
        } catch (Exception e) {
            Log.e("ERROR", e.toString());
        }
}

@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode != LINE_REQUEST_CODE) {
            return;
        }

        try {
            final LineLoginResult result = LineLoginApi.getLoginResultFromIntent(data);

            switch (result.getResponseCode()) {
                case SUCCESS:
                    final LineAccessToken accessToken = result.getLineCredential().getAccessToken();

                    final Intent intent = new Intent(getContext(), WebLineLoginActivity.class);
                    final Runnable showLineLoginActivity = new Runnable() {
                        @Override
                        public void run() {
                            intent.putExtra(WebLineLoginActivity.INTENT_EXTRA_ACCESS_TOKEN, accessToken.getAccessToken());
                            intent.putExtra(WebLineLoginActivity.INTENT_EXTRA_EXPIRE, accessToken.getEstimatedExpirationTimeMillis());
                            LoginCheckAndLoginActivityV2.copyRedirectIntent(getIntent(), intent);
                            startActivity(intent);
                            finish();
                        }
                    };

                    if (getIntent().getBooleanExtra(WebLineLoginActivity.INTENT_EXTRA_LINK_IN_MODE, false)) {
                        ApiChannelTask<SignatureApiResult> task = new SignatureGetApiChannelTask(intent, showLineLoginActivity);
                        intent.putExtra(WebLineLoginActivity.INTENT_EXTRA_LINK_IN_MODE, true);
                        Channel.getApiRequestChannel().putRequest(task, Channel.Priority.HIGH);
                    } else {
                        getContext().getUiThreadHandler().post(showLineLoginActivity);
                    }

                    // register gcm

                    break;
                default:
                    getContext().getUiThreadHandler().post(new Runnable() {
                        @Override
                        public void run() {
                            // show login form
                        }
                    });
                    break;
            }
        } catch (NullPointerException e) {
            Crashlytics.logException(e);
        }
}
```

**Comment by kazuki-ma** [comment]
Thank you providing repro.
We will check it and reply later.

**Comment by HirotoIchinose** [comment]
@kazuki-ma Thank you.
I'd like to know when you would reply.

**Comment by YichingChiang** [comment]
Hi, @HirotoIchinose 
We have released a new SDK.
[LINE SDK for Android 4.0.7 released](https://developers.line.me/en/news/#line-sdk-for-android-4-0-7-2018-02-06)
Could you give it a try?

**Comment by HirotoIchinose** [comment]
@YichingChiang 
Thank you for support!!!
We'll try it.

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
