### ISSUE TITLE
LINE LOGIN ISSUE

### ISSUE THREAD

**Issue by abyss99** [line/line-platform-feedback#95]
Hello.
We are using android line login sdk 4.0.8.
I can't reproduce by myself but the following logs are being recorded in the error log system. Can you check them?

```
LINE Login failed. error : LineApiError{httpResponseCode=-1, message='android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://access.line.me/dialog/oauth/weblogin?response_type=code&client_id=1401600689&state=E1TAtJmJC-o&otpId=9wJO/C7LN290HsnVHgXDmZzIi/Q=&redirect_uri=intent://result#Intent;package=com.naver.linewebtoon;scheme=lineauth;end pkg=jp.naver.line.android }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1815)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1513)
at android.app.Activity.startActivityForResult(Activity.java:3933)
at android.app.Activity.startActivityForResult(Activity.java:3881)
at android.app.Activity.startActivity(Activity.java:4204)
at com.linecorp.linesdk.auth.internal.j.onPostExecute(SourceFile:1127)
at android.os.AsyncTask.finish(AsyncTask.java:636)
at android.os.AsyncTask.access$500(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5910)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
'}
```

**Comment by vinicioanthone** [comment]
Dear LINE Platform user,

Thank you for taking the time to report this issue. Unfortunately, we're unable to follow up on it right now. The reason is that we've created too many feedback channels to track and solve issues as effectively as we want. That's why we've decided to do the following:

* On **February 15, 2019**, we'll be archiving this repository, including all issues.
* We'll close all open issues, regardless of whether they've been solved.

We'll keep the repository public so you can still read it. However, you won't be able to report new issues or edit existing ones here on GitHub. Instead, you can report LINE Platform issues on our [LINE Developers forum](https://www.line-community.me/questions). Please feel free to report your existing issue again if it hasn't been solved. We'll do our best to respond promptly.

We apologize for responding to your issue in such a disappointing way. User feedback is truly important to us — which is why we want to make sure we can follow up on it effectively. Reducing the number of feedback channels is part of that. We hope you understand and look forward to seeing you on [the forum](https://www.line-community.me/).

Sincerely,

The LINE Platform team
